# Generated by Django 4.1.4 on 2023-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_avatar_worksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='tags',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
