# Generated by Django 4.1.4 on 2023-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tag_remove_worksheet_tags_worksheet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='image',
            field=models.ImageField(default='worksheets/default_image.png', upload_to='worksheets'),
        ),
    ]
