# Generated by Django 4.1.4 on 2023-03-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
