# Generated by Django 4.1.7 on 2023-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
