# Generated by Django 4.1.7 on 2023-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
