# Generated by Django 4.1.7 on 2023-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_dislike_rename_likes_like_delete_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksheet',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
