# Generated by Django 4.1.7 on 2023-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_worksheet_dislikes_worksheet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
