# Generated by Django 4.2 on 2023-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_worksheet_dislikes_alter_worksheet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TimeField(),
        ),
    ]
